version: '3'

services:
  flask_app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
    environment:
      - MYSQL_HOST=mysql_db  # This should match the mysql_db service name
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=flask_db

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flask_db
    ports:
      - "3306:3306"

networks:
  default:
    driver: bridge
