version: '3'

services:
  flask_app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flask_db
    ports:
      - "3306:3306"
